// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantReservation.API.Data;

#nullable disable

namespace RestaurantReservation.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613125747_SeedComprehensiveMenu")]
    partial class SeedComprehensiveMenu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("RestaurantReservation.API.Models.MenuItem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = "menu-truffle-fries",
                            Category = "Appetizer",
                            Description = "Crispy golden fries tossed in white truffle oil, grated parmesan cheese, and fresh parsley.",
                            IsAvailable = true,
                            Name = "Truffle Parmesan Fries",
                            Price = 9.50m
                        },
                        new
                        {
                            Id = "menu-calamari",
                            Category = "Appetizer",
                            Description = "Lightly battered calamari rings served with a tangy lemon-garlic aioli.",
                            IsAvailable = true,
                            Name = "Crispy Calamari",
                            Price = 13.00m
                        },
                        new
                        {
                            Id = "menu-margherita",
                            Category = "Main",
                            Description = "Classic neapolitan style pizza with fresh mozzarella, san marzano tomatoes, and fresh basil.",
                            IsAvailable = true,
                            Name = "Margherita Pizza",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = "menu-salmon",
                            Category = "Main",
                            Description = "Atlantic salmon fillet served over a bed of garlic herb quinoa and grilled asparagus.",
                            IsAvailable = true,
                            Name = "Pan-Seared Salmon",
                            Price = 24.50m
                        },
                        new
                        {
                            Id = "menu-ribeye",
                            Category = "Main",
                            Description = "12oz choice ribeye grilled to perfection, served with garlic mashed potatoes and rosemary butter.",
                            IsAvailable = true,
                            Name = "Ribeye Steak",
                            Price = 32.00m
                        },
                        new
                        {
                            Id = "menu-lava-cake",
                            Category = "Dessert",
                            Description = "Rich chocolate cake with a warm flowing center, served with vanilla bean gelato.",
                            IsAvailable = true,
                            Name = "Molten Lava Cake",
                            Price = 8.50m
                        },
                        new
                        {
                            Id = "menu-cheesecake",
                            Category = "Dessert",
                            Description = "Classic dense and creamy cheesecake with a sweet strawberry compote drizzle.",
                            IsAvailable = true,
                            Name = "New York Cheesecake",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = "menu-mojito",
                            Category = "Drink",
                            Description = "Refreshing blend of white rum, fresh lime juice, muddled mint leaves, and club soda.",
                            IsAvailable = true,
                            Name = "Classic Mojito",
                            Price = 11.00m
                        });
                });

            modelBuilder.Entity("RestaurantReservation.API.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("PartySize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReservationDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TableId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("RestaurantReservation.API.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TableNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TableNumber")
                        .IsUnique();

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("RestaurantReservation.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RestaurantReservation.API.Models.Reservation", b =>
                {
                    b.HasOne("RestaurantReservation.API.Models.Table", "Table")
                        .WithMany("Reservations")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantReservation.API.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestaurantReservation.API.Models.Table", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("RestaurantReservation.API.Models.User", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
